# 1. Import and Install Dependencies

In [1]:
#!pip install tensorflow==2.4.1 tensorflow-gpu==2.4.1 opencv-python mediapipe sklearn matplotlib

In [1]:
import cv2
import numpy as np
import os
from matplotlib import pyplot as plt
import time
import mediapipe as mp
from tensorflow import keras

# 2. Keypoints using MP Holistic

In [2]:
mp_holistic = mp.solutions.holistic # Holistic model
mp_drawing = mp.solutions.drawing_utils # Drawing utilities

In [3]:
def mediapipe_detection(image, model):
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB) # COLOR CONVERSION BGR 2 RGB
    image.flags.writeable = False                  # Image is no longer writeable
    results = model.process(image)                 # Make prediction
    image.flags.writeable = True                   # Image is now writeable 
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR) # COLOR COVERSION RGB 2 BGR
    return image, results

In [4]:
def draw_landmarks(image, results):
    #mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION) # Draw face connections
    #mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS) # Draw pose connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS) # Draw right hand connections

In [5]:
def draw_styled_landmarks(image, results):
    # Draw face connections
    #mp_drawing.draw_landmarks(image, results.face_landmarks, mp_holistic.FACEMESH_TESSELATION, 
                             #mp_drawing.DrawingSpec(color=(80,110,10), thickness=1, circle_radius=1), 
                             #mp_drawing.DrawingSpec(color=(80,256,121), thickness=1, circle_radius=1)
                             #) 
    # Draw pose connections
    #mp_drawing.draw_landmarks(image, results.pose_landmarks, mp_holistic.POSE_CONNECTIONS,
    #                         mp_drawing.DrawingSpec(color=(80,22,10), thickness=2, circle_radius=4), 
    #                         mp_drawing.DrawingSpec(color=(80,44,121), thickness=2, circle_radius=2)
    #                         ) 
    # Draw left hand connections
    mp_drawing.draw_landmarks(image, results.left_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(121,22,76), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(121,44,250), thickness=2, circle_radius=2)
                             ) 
    # Draw right hand connections  
    mp_drawing.draw_landmarks(image, results.right_hand_landmarks, mp_holistic.HAND_CONNECTIONS, 
                             mp_drawing.DrawingSpec(color=(245,117,66), thickness=2, circle_radius=4), 
                             mp_drawing.DrawingSpec(color=(245,66,230), thickness=2, circle_radius=2)
                             ) 

In [6]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    while cap.isOpened():

        # Read feed
        ret, frame = cap.read()
        print(frame)
        # Make detections
        image, results = mediapipe_detection(frame, holistic)
        #print(results)
        
        # Draw landmarks
        draw_styled_landmarks(image, results)

        # Show to screen
        cv2.imshow('OpenCV Feed', image)

        # Break gracefully
        if cv2.waitKey(10) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

[[[157 172 154]
  [156 170 152]
  [159 171 152]
  ...
  [114 119 121]
  [121 124 126]
  [119 119 122]]

 [[164 177 159]
  [159 172 154]
  [162 173 154]
  ...
  [120 124 125]
  [127 129 130]
  [124 125 126]]

 [[167 175 159]
  [166 174 158]
  [172 180 164]
  ...
  [124 127 125]
  [129 131 129]
  [126 126 125]]

 ...

 [[153 168 170]
  [153 168 169]
  [152 166 167]
  ...
  [ 57  57  75]
  [ 66  66  80]
  [ 75  73  85]]

 [[152 165 169]
  [151 165 168]
  [153 166 168]
  ...
  [ 43  45  63]
  [ 42  43  58]
  [ 38  38  51]]

 [[153 165 170]
  [150 162 166]
  [155 167 169]
  ...
  [ 40  43  61]
  [ 41  44  59]
  [ 37  38  51]]]
[[[178 186 162]
  [172 180 157]
  [171 179 160]
  ...
  [143 135 153]
  [141 132 152]
  [140 130 153]]

 [[179 187 163]
  [174 182 159]
  [174 182 162]
  ...
  [140 132 149]
  [143 134 153]
  [145 136 157]]

 [[186 193 169]
  [178 185 162]
  [175 183 163]
  ...
  [144 139 151]
  [150 143 158]
  [153 145 162]]

 ...

 [[170 176 173]
  [170 175 173]
  [169 175 174]
  ..

[[[172 182 165]
  [168 178 161]
  [168 178 161]
  ...
  [130 139 137]
  [131 138 138]
  [129 133 135]]

 [[175 185 166]
  [172 182 163]
  [172 182 163]
  ...
  [126 136 134]
  [125 133 133]
  [123 129 131]]

 [[180 189 169]
  [178 187 167]
  [178 187 167]
  ...
  [126 137 135]
  [124 134 134]
  [124 134 135]]

 ...

 [[168 178 176]
  [170 180 178]
  [168 178 178]
  ...
  [ 64  61  77]
  [ 70  66  82]
  [ 74  68  83]]

 [[171 178 177]
  [173 180 179]
  [172 180 180]
  ...
  [ 61  57  75]
  [ 66  61  78]
  [ 65  58  75]]

 [[170 176 175]
  [172 178 177]
  [170 177 177]
  ...
  [ 57  53  71]
  [ 63  58  76]
  [ 59  52  69]]]
[[[171 183 154]
  [171 180 153]
  [171 176 151]
  ...
  [140 144 155]
  [138 143 154]
  [134 140 152]]

 [[170 181 154]
  [171 181 155]
  [176 181 156]
  ...
  [137 143 153]
  [136 143 153]
  [132 139 149]]

 [[173 183 160]
  [171 180 157]
  [174 180 158]
  ...
  [131 137 146]
  [128 136 145]
  [129 137 147]]

 ...

 [[170 179 177]
  [168 177 174]
  [170 179 177]
  ..

[[[181 176 161]
  [176 172 157]
  [176 176 160]
  ...
  [139 143 164]
  [132 137 156]
  [131 137 154]]

 [[183 178 162]
  [183 179 164]
  [185 185 169]
  ...
  [134 140 159]
  [128 135 151]
  [127 134 149]]

 [[191 186 170]
  [191 187 172]
  [191 190 174]
  ...
  [132 141 154]
  [128 138 149]
  [129 140 149]]

 ...

 [[168 179 179]
  [167 178 178]
  [165 176 176]
  ...
  [ 59  61  76]
  [ 62  65  77]
  [ 72  74  84]]

 [[167 179 177]
  [167 179 178]
  [166 177 177]
  ...
  [ 46  48  68]
  [ 48  50  68]
  [ 62  63  79]]

 [[166 179 177]
  [167 180 178]
  [167 180 179]
  ...
  [ 47  48  72]
  [ 44  45  68]
  [ 55  56  77]]]
[[[176 178 165]
  [179 182 170]
  [177 182 170]
  ...
  [136 140 148]
  [139 140 148]
  [137 135 144]]

 [[179 181 169]
  [179 182 171]
  [175 180 169]
  ...
  [131 135 143]
  [136 138 146]
  [138 137 146]]

 [[180 182 173]
  [180 183 174]
  [178 182 173]
  ...
  [133 138 144]
  [137 140 147]
  [140 142 150]]

 ...

 [[166 181 177]
  [165 180 176]
  [165 180 176]
  ..

[[[166 183 153]
  [164 180 149]
  [163 177 145]
  ...
  [118 129 130]
  [115 127 125]
  [118 130 125]]

 [[163 179 148]
  [166 182 151]
  [168 182 151]
  ...
  [116 127 128]
  [116 127 125]
  [119 130 125]]

 [[179 193 162]
  [178 192 161]
  [177 188 158]
  ...
  [115 123 126]
  [122 130 131]
  [125 132 131]]

 ...

 [[157 178 166]
  [156 177 166]
  [156 176 167]
  ...
  [ 51  53  73]
  [ 60  62  82]
  [ 67  68  88]]

 [[156 179 168]
  [154 177 167]
  [156 177 169]
  ...
  [ 46  48  68]
  [ 54  56  76]
  [ 61  64  83]]

 [[155 179 169]
  [153 177 167]
  [154 176 168]
  ...
  [ 48  49  69]
  [ 45  48  67]
  [ 42  46  65]]]
[[[178 174 159]
  [172 169 154]
  [172 174 158]
  ...
  [144 144 151]
  [142 143 150]
  [142 144 151]]

 [[181 179 163]
  [179 178 162]
  [179 182 166]
  ...
  [143 143 149]
  [143 145 150]
  [143 146 151]]

 [[183 182 165]
  [182 182 165]
  [184 187 169]
  ...
  [142 143 146]
  [141 143 146]
  [140 144 146]]

 ...

 [[166 182 181]
  [163 179 178]
  [161 177 176]
  ..

[[[162 177 164]
  [162 177 163]
  [164 177 163]
  ...
  [130 138 139]
  [132 140 141]
  [135 143 144]]

 [[166 179 168]
  [166 178 167]
  [166 177 165]
  ...
  [128 136 136]
  [131 139 139]
  [133 141 141]]

 [[173 180 173]
  [175 181 174]
  [178 183 175]
  ...
  [129 136 136]
  [132 138 138]
  [134 139 139]]

 ...

 [[159 173 171]
  [160 174 172]
  [163 176 174]
  ...
  [ 55  54  77]
  [ 63  62  85]
  [ 68  66  89]]

 [[160 179 176]
  [158 177 174]
  [160 178 175]
  ...
  [ 55  55  76]
  [ 49  48  70]
  [ 54  52  75]]

 [[154 177 173]
  [156 178 174]
  [160 180 177]
  ...
  [ 60  60  80]
  [ 46  46  67]
  [ 55  53  76]]]
[[[167 177 154]
  [166 175 152]
  [165 174 151]
  ...
  [132 146 142]
  [128 143 139]
  [129 145 141]]

 [[169 179 156]
  [171 180 157]
  [174 181 160]
  ...
  [129 142 138]
  [127 141 137]
  [129 143 139]]

 [[184 194 171]
  [184 193 171]
  [186 192 171]
  ...
  [133 142 140]
  [134 143 141]
  [136 145 143]]

 ...

 [[162 178 177]
  [166 182 181]
  [158 174 173]
  ..

[[[169 171 165]
  [166 168 162]
  [166 169 161]
  ...
  [138 140 137]
  [138 137 136]
  [145 141 142]]

 [[172 174 168]
  [174 177 170]
  [175 179 171]
  ...
  [143 145 143]
  [143 142 142]
  [147 144 146]]

 [[172 176 168]
  [174 178 170]
  [177 181 172]
  ...
  [146 147 147]
  [145 145 146]
  [148 146 148]]

 ...

 [[159 180 172]
  [160 179 172]
  [163 181 175]
  ...
  [ 52  64  65]
  [ 57  67  67]
  [ 65  75  73]]

 [[158 177 170]
  [160 178 171]
  [163 180 174]
  ...
  [ 54  66  67]
  [ 47  58  59]
  [ 52  62  62]]

 [[159 177 170]
  [159 177 170]
  [157 173 168]
  ...
  [ 55  68  69]
  [ 45  57  58]
  [ 46  58  58]]]
[[[149 187 151]
  [145 179 144]
  [153 177 146]
  ...
  [145 144 153]
  [144 142 151]
  [145 142 151]]

 [[149 185 149]
  [147 179 145]
  [160 182 151]
  ...
  [143 141 149]
  [144 141 149]
  [145 142 150]]

 [[171 198 165]
  [171 194 162]
  [181 197 169]
  ...
  [141 138 145]
  [141 137 145]
  [143 139 147]]

 ...

 [[170 180 178]
  [168 177 176]
  [169 178 178]
  ..

[[[171 179 155]
  [170 178 155]
  [175 181 160]
  ...
  [148 148 147]
  [139 140 138]
  [140 141 138]]

 [[171 179 156]
  [170 177 156]
  [175 180 161]
  ...
  [143 143 143]
  [141 141 141]
  [142 143 141]]

 [[177 183 162]
  [176 182 161]
  [181 185 166]
  ...
  [147 148 150]
  [145 145 148]
  [142 143 144]]

 ...

 [[168 180 178]
  [168 180 178]
  [166 179 177]
  ...
  [ 55  66  68]
  [ 56  67  67]
  [ 65  76  73]]

 [[166 177 175]
  [166 177 175]
  [166 177 175]
  ...
  [ 52  62  67]
  [ 53  64  65]
  [ 58  70  68]]

 [[164 175 173]
  [166 176 174]
  [167 177 175]
  ...
  [ 51  61  67]
  [ 48  60  62]
  [ 49  62  61]]]
[[[183 175 165]
  [178 173 161]
  [174 176 164]
  ...
  [120 132 134]
  [123 136 138]
  [126 140 142]]

 [[183 176 166]
  [178 174 163]
  [175 176 166]
  ...
  [121 133 135]
  [122 135 137]
  [124 137 139]]

 [[187 181 171]
  [184 179 170]
  [183 183 173]
  ...
  [119 131 133]
  [123 135 137]
  [123 135 137]]

 ...

 [[173 181 187]
  [167 175 181]
  [167 176 180]
  ..

[[[176 182 163]
  [169 175 157]
  [172 177 161]
  ...
  [126 141 127]
  [127 145 123]
  [129 149 120]]

 [[175 182 162]
  [170 176 157]
  [174 180 163]
  ...
  [129 143 131]
  [128 144 126]
  [130 148 124]]

 [[185 191 173]
  [186 192 174]
  [191 197 180]
  ...
  [136 148 140]
  [134 148 138]
  [135 150 137]]

 ...

 [[166 182 175]
  [169 184 179]
  [165 180 176]
  ...
  [ 60  61  79]
  [ 64  65  82]
  [ 66  69  84]]

 [[165 180 172]
  [168 183 176]
  [165 178 173]
  ...
  [ 51  54  72]
  [ 51  56  72]
  [ 55  60  75]]

 [[165 181 171]
  [170 184 176]
  [165 177 171]
  ...
  [ 50  54  72]
  [ 42  49  65]
  [ 44  53  67]]]
[[[177 181 169]
  [175 179 166]
  [172 177 163]
  ...
  [120 133 121]
  [125 138 127]
  [120 134 123]]

 [[184 188 176]
  [182 186 174]
  [178 183 169]
  ...
  [117 130 119]
  [121 133 124]
  [121 134 125]]

 [[184 188 176]
  [185 189 177]
  [186 191 177]
  ...
  [118 131 123]
  [118 131 123]
  [117 131 123]]

 ...

 [[155 180 172]
  [155 179 172]
  [154 176 170]
  ..

[[[181 194 152]
  [180 192 151]
  [177 187 151]
  ...
  [138 146 143]
  [140 146 145]
  [136 142 141]]

 [[175 187 145]
  [176 188 146]
  [176 186 149]
  ...
  [141 147 145]
  [142 148 147]
  [138 144 143]]

 [[187 196 156]
  [187 196 157]
  [186 193 158]
  ...
  [143 147 146]
  [144 149 148]
  [141 146 145]]

 ...

 [[170 186 180]
  [173 188 183]
  [172 186 181]
  ...
  [ 62  64  75]
  [ 66  67  78]
  [ 78  77  87]]

 [[169 184 177]
  [170 184 178]
  [167 181 176]
  ...
  [ 56  59  73]
  [ 54  55  68]
  [ 63  63  76]]

 [[173 187 180]
  [170 183 177]
  [165 178 173]
  ...
  [ 57  61  76]
  [ 49  52  67]
  [ 53  54  68]]]
[[[169 175 174]
  [169 176 175]
  [171 177 177]
  ...
  [124 135 130]
  [123 134 127]
  [122 133 124]]

 [[172 178 177]
  [174 180 179]
  [174 180 180]
  ...
  [122 133 128]
  [123 133 127]
  [120 131 123]]

 [[181 185 183]
  [183 187 185]
  [183 188 187]
  ...
  [123 132 129]
  [125 134 130]
  [121 131 125]]

 ...

 [[163 182 179]
  [160 179 176]
  [162 179 176]
  ..

[[[165 176 168]
  [165 176 167]
  [170 180 168]
  ...
  [111 124 132]
  [114 124 134]
  [119 127 138]]

 [[170 180 174]
  [170 180 173]
  [175 184 174]
  ...
  [111 124 132]
  [114 124 134]
  [117 125 135]]

 [[175 184 178]
  [176 185 179]
  [181 188 180]
  ...
  [117 129 136]
  [120 130 138]
  [121 129 139]]

 ...

 [[165 174 177]
  [165 174 177]
  [167 175 178]
  ...
  [ 64  65  82]
  [ 70  72  86]
  [ 76  79  90]]

 [[166 176 176]
  [167 176 176]
  [166 175 175]
  ...
  [ 63  64  84]
  [ 67  68  85]
  [ 70  71  87]]

 [[167 178 175]
  [167 177 174]
  [165 175 172]
  ...
  [ 58  58  79]
  [ 58  58  78]
  [ 60  59  78]]]
[[[186 179 173]
  [184 178 170]
  [182 177 168]
  ...
  [137 147 144]
  [134 147 142]
  [127 143 136]]

 [[185 181 174]
  [183 179 171]
  [181 178 169]
  ...
  [137 147 144]
  [136 148 143]
  [130 144 137]]

 [[181 179 171]
  [183 181 173]
  [185 185 175]
  ...
  [140 147 146]
  [138 147 144]
  [134 144 139]]

 ...

 [[ 72  76  74]
  [ 71  74  72]
  [ 70  72  69]
  ..

[[[169 173 174]
  [170 174 173]
  [169 172 170]
  ...
  [130 136 132]
  [131 137 135]
  [131 138 137]]

 [[168 173 171]
  [172 176 174]
  [173 176 173]
  ...
  [133 138 134]
  [131 136 135]
  [129 133 134]]

 [[171 177 172]
  [173 178 173]
  [174 179 172]
  ...
  [137 140 139]
  [136 138 139]
  [134 134 137]]

 ...

 [[141 160 167]
  [149 167 174]
  [142 157 164]
  ...
  [ 59  61  81]
  [ 63  64  85]
  [ 70  69  92]]

 [[148 165 171]
  [152 168 174]
  [125 138 146]
  ...
  [ 60  60  79]
  [ 59  58  78]
  [ 64  61  83]]

 [[147 162 167]
  [141 156 162]
  [122 134 142]
  ...
  [ 58  58  76]
  [ 54  52  72]
  [ 58  53  74]]]
[[[173 176 161]
  [170 174 159]
  [169 174 159]
  ...
  [121 137 147]
  [119 135 146]
  [118 134 146]]

 [[173 174 160]
  [173 175 161]
  [173 177 162]
  ...
  [122 137 147]
  [121 137 147]
  [122 137 149]]

 [[184 184 171]
  [184 185 172]
  [183 185 172]
  ...
  [127 140 148]
  [127 141 150]
  [127 141 150]]

 ...

 [[156 166 166]
  [156 166 167]
  [159 168 171]
  ..

[[[173 170 169]
  [170 169 168]
  [164 168 166]
  ...
  [135 138 142]
  [131 133 137]
  [132 133 137]]

 [[177 176 175]
  [174 175 173]
  [169 173 171]
  ...
  [133 135 139]
  [129 130 134]
  [132 131 135]]

 [[175 178 175]
  [175 178 176]
  [174 178 176]
  ...
  [136 136 139]
  [133 132 135]
  [135 133 136]]

 ...

 [[159 172 170]
  [158 172 170]
  [157 171 169]
  ...
  [ 55  67  75]
  [ 48  61  66]
  [ 58  72  74]]

 [[157 170 168]
  [159 172 170]
  [157 170 168]
  ...
  [ 48  60  69]
  [ 44  57  63]
  [ 48  63  65]]

 [[158 170 168]
  [161 173 171]
  [160 172 170]
  ...
  [ 42  54  63]
  [ 42  56  62]
  [ 42  58  60]]]
[[[171 168 163]
  [171 170 163]
  [170 172 162]
  ...
  [115 118 122]
  [121 120 126]
  [124 121 127]]

 [[177 174 169]
  [180 179 172]
  [178 180 170]
  ...
  [117 119 124]
  [122 121 127]
  [124 120 128]]

 [[174 173 167]
  [178 178 171]
  [181 183 174]
  ...
  [120 121 127]
  [122 121 128]
  [123 119 127]]

 ...

 [[154 166 167]
  [153 165 166]
  [153 166 167]
  ..

[[[164 167 151]
  [158 161 146]
  [163 164 154]
  ...
  [124 120 120]
  [121 116 117]
  [122 117 118]]

 [[173 176 163]
  [167 170 158]
  [168 170 161]
  ...
  [117 113 114]
  [118 114 115]
  [118 114 115]]

 [[174 177 167]
  [170 173 164]
  [170 172 165]
  ...
  [115 112 114]
  [119 116 118]
  [119 115 117]]

 ...

 [[144 160 160]
  [142 159 159]
  [142 159 160]
  ...
  [ 58  60  77]
  [ 61  63  77]
  [ 66  68  79]]

 [[151 164 165]
  [152 165 166]
  [150 164 166]
  ...
  [ 55  57  74]
  [ 54  56  71]
  [ 58  59  72]]

 [[155 166 166]
  [155 166 167]
  [152 164 165]
  ...
  [ 45  46  64]
  [ 43  45  60]
  [ 50  51  64]]]
[[[166 168 162]
  [159 161 155]
  [161 165 160]
  ...
  [111 115 118]
  [109 115 114]
  [111 119 115]]

 [[164 166 160]
  [164 167 161]
  [170 175 170]
  ...
  [116 120 122]
  [114 120 119]
  [112 119 115]]

 [[168 171 166]
  [171 175 170]
  [173 179 175]
  ...
  [109 112 116]
  [111 117 116]
  [115 122 118]]

 ...

 [[153 166 167]
  [157 171 171]
  [154 168 167]
  ..

# 3. Extract Keypoint Values

In [7]:
def extract_keypoints(results):
    #pose = np.array([[res.x, res.y, res.z, res.visibility] for res in results.pose_landmarks.landmark]).flatten() if results.pose_landmarks else np.zeros(33*4)
    #face = np.array([[res.x, res.y, res.z] for res in results.face_landmarks.landmark]).flatten() if results.face_landmarks else np.zeros(468*3)
    lh = np.array([[res.x, res.y, res.z] for res in results.left_hand_landmarks.landmark]).flatten() if results.left_hand_landmarks else np.zeros(21*3)
    rh = np.array([[res.x, res.y, res.z] for res in results.right_hand_landmarks.landmark]).flatten() if results.right_hand_landmarks else np.zeros(21*3)
    return np.concatenate([lh, rh])

# 4. Setup Folders for Collection

In [8]:
# Path for exported data, numpy arrays
DATA_PATH = os.path.join('MP_Data') 

# Actions that we try to detect
actions = np.array(['i love you','hello', 'I', 'to', 'forgive', 'hill', 'meet', 'want', 'yes', 'go'])

# Thirty videos worth of data
no_sequences = 30

# Videos are going to be 30 frames in length
sequence_length = 30

In [9]:
# hello
## 0
## 1
## 2
## ...
## 29
# thanks

# I love you

In [10]:
for action in actions: 
    for sequence in range(no_sequences):
        try: 
            os.makedirs(os.path.join(DATA_PATH, action, str(sequence)))
        except:
            pass

# 5. Collect Keypoint Values for Training and Testing

In [11]:
cap = cv2.VideoCapture(0)
# Set mediapipe model 
with mp_holistic.Holistic(min_detection_confidence=0.5, min_tracking_confidence=0.5) as holistic:
    
    # NEW LOOP
    # Loop through actions
    for action in actions:
        # Loop through sequences aka videos
        for sequence in range(no_sequences):
            # Loop through video length aka sequence length
            for frame_num in range(sequence_length):

                # Read feed
                ret, frame = cap.read()

                # Make detections
                image, results = mediapipe_detection(frame, holistic)
#                 print(results)

                # Draw landmarks
                draw_styled_landmarks(image, results)
                
                # NEW Apply wait logic
                if frame_num == 0: 
                    cv2.putText(image, 'STARTING COLLECTION', (120,200), 
                               cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255, 0), 4, cv2.LINE_AA)
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                    cv2.waitKey(2000)
                else: 
                    cv2.putText(image, 'Collecting frames for {} Video Number {}'.format(action, sequence), (15,12), 
                               cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 0, 255), 1, cv2.LINE_AA)
                    # Show to screen
                    cv2.imshow('OpenCV Feed', image)
                
                # NEW Export keypoints
                keypoints = extract_keypoints(results)
                npy_path = os.path.join(DATA_PATH, action, str(sequence), str(frame_num))
                np.save(npy_path, keypoints)

                # Break gracefully
                if cv2.waitKey(10) & 0xFF == ord('q'):
                    break
                    
    cap.release()
    cv2.destroyAllWindows()

In [12]:
cap.release()
cv2.destroyAllWindows()